version: '3'
services:
  todofront:
    image: todofrontend
    ports:
      - 3000:80
    environment:
        - REACT_APP_API_HOST=todoback
    depends_on:
      - todoback
  todoback:
    image: todobackend
    ports:
      - 3001:80
  todotests:
    image: todotests
    environment:
      - FRONT_HOST=todofront
    depends_on:
      - todofront
      - todoback